export interface Country {
  name: string;
  code: string;
  flag: string;
  dial_code: string;
}
export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", dial_code: "+93" },
  { name: "Albania", code: "AL", flag: "🇦🇱", dial_code: "+355" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", dial_code: "+213" },
  { name: "Andorra", code: "AD", flag: "🇦🇩", dial_code: "+376" },
  { name: "Angola", code: "AO", flag: "🇦🇴", dial_code: "+244" },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", dial_code: "+1-268" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", dial_code: "+54" },
  { name: "Armenia", code: "AM", flag: "🇦🇲", dial_code: "+374" },
  { name: "Australia", code: "AU", flag: "🇦🇺", dial_code: "+61" },
  { name: "Austria", code: "AT", flag: "🇦🇹", dial_code: "+43" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", dial_code: "+994" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", dial_code: "+1-242" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", dial_code: "+973" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", dial_code: "+880" },
  { name: "Barbados", code: "BB", flag: "🇧🇧", dial_code: "+1-246" },
  { name: "Belarus", code: "BY", flag: "🇧🇾", dial_code: "+375" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", dial_code: "+32" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", dial_code: "+501" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", dial_code: "+229" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", dial_code: "+975" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", dial_code: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", dial_code: "+387" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", dial_code: "+267" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", dial_code: "+55" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", dial_code: "+673" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", dial_code: "+359" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", dial_code: "+226" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", dial_code: "+257" },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻", dial_code: "+238" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", dial_code: "+855" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", dial_code: "+237" },
  { name: "Canada", code: "CA", flag: "🇨🇦", dial_code: "+1" },
  {
    name: "Central African Republic",
    code: "CF",
    flag: "🇨🇫",
    dial_code: "+236",
  },
  { name: "Chad", code: "TD", flag: "🇹🇩", dial_code: "+235" },
  { name: "Chile", code: "CL", flag: "🇨🇱", dial_code: "+56" },
  { name: "China", code: "CN", flag: "🇨🇳", dial_code: "+86" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", dial_code: "+57" },
  { name: "Comoros", code: "KM", flag: "🇰🇲", dial_code: "+269" },
  {
    name: "Congo (Congo-Brazzaville)",
    code: "CG",
    flag: "🇨🇬",
    dial_code: "+242",
  },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", dial_code: "+506" },
  { name: "Croatia", code: "HR", flag: "🇭🇷", dial_code: "+385" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", dial_code: "+53" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", dial_code: "+357" },
  {
    name: "Czechia (Czech Republic)",
    code: "CZ",
    flag: "🇨🇿",
    dial_code: "+420",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    flag: "🇨🇩",
    dial_code: "+243",
  },
  { name: "Denmark", code: "DK", flag: "🇩🇰", dial_code: "+45" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", dial_code: "+253" },
  { name: "Dominica", code: "DM", flag: "🇩🇲", dial_code: "+1-767" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", dial_code: "+1-809" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", dial_code: "+593" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", dial_code: "+20" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", dial_code: "+503" },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", dial_code: "+240" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", dial_code: "+291" },
  { name: "Estonia", code: "EE", flag: "🇪🇪", dial_code: "+372" },
  {
    name: "Eswatini (fmr. Swaziland)",
    code: "SZ",
    flag: "🇸🇿",
    dial_code: "+268",
  },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", dial_code: "+251" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", dial_code: "+679" },
  { name: "Finland", code: "FI", flag: "🇫🇮", dial_code: "+358" },
  { name: "France", code: "FR", flag: "🇫🇷", dial_code: "+33" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", dial_code: "+241" },
  { name: "Gambia", code: "GM", flag: "🇬🇲", dial_code: "+220" },
  { name: "Georgia", code: "GE", flag: "🇬🇪", dial_code: "+995" },
  { name: "Germany", code: "DE", flag: "🇩🇪", dial_code: "+49" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", dial_code: "+233" },
  { name: "Greece", code: "GR", flag: "🇬🇷", dial_code: "+30" },
  { name: "Grenada", code: "GD", flag: "🇬🇩", dial_code: "+1-473" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", dial_code: "+502" },
  { name: "Guinea", code: "GN", flag: "🇬🇳", dial_code: "+224" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", dial_code: "+245" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", dial_code: "+592" },
  { name: "Haiti", code: "HT", flag: "🇭🇹", dial_code: "+509" },
  { name: "Holy See", code: "VA", flag: "🇻🇦", dial_code: "+39" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", dial_code: "+504" },
  { name: "Hungary", code: "HU", flag: "🇭🇺", dial_code: "+36" },
  { name: "Iceland", code: "IS", flag: "🇮🇸", dial_code: "+354" },
  { name: "India", code: "IN", flag: "🇮🇳", dial_code: "+91" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", dial_code: "+62" },
  { name: "Iran", code: "IR", flag: "🇮🇷", dial_code: "+98" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", dial_code: "+964" },
  { name: "Ireland", code: "IE", flag: "🇮🇪", dial_code: "+353" },
  { name: "Israel", code: "IL", flag: "🇮🇱", dial_code: "+972" },
  { name: "Italy", code: "IT", flag: "🇮🇹", dial_code: "+39" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮", dial_code: "+225" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", dial_code: "+1-876" },
  { name: "Japan", code: "JP", flag: "🇯🇵", dial_code: "+81" },
  { name: "Jordan", code: "JO", flag: "🇯🇴", dial_code: "+962" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", dial_code: "+7" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", dial_code: "+254" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", dial_code: "+686" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", dial_code: "+965" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", dial_code: "+996" },
  { name: "Laos", code: "LA", flag: "🇱🇦", dial_code: "+856" },
  { name: "Latvia", code: "LV", flag: "🇱🇻", dial_code: "+371" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", dial_code: "+961" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", dial_code: "+266" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", dial_code: "+231" },
  { name: "Libya", code: "LY", flag: "🇱🇾", dial_code: "+218" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", dial_code: "+423" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", dial_code: "+370" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", dial_code: "+352" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", dial_code: "+261" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", dial_code: "+265" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", dial_code: "+60" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", dial_code: "+960" },
  { name: "Mali", code: "ML", flag: "🇲🇱", dial_code: "+223" },
  { name: "Malta", code: "MT", flag: "🇲🇹", dial_code: "+356" },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", dial_code: "+692" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", dial_code: "+222" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", dial_code: "+230" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", dial_code: "+52" },
  { name: "Micronesia", code: "FM", flag: "🇫🇲", dial_code: "+691" },
  { name: "Moldova", code: "MD", flag: "🇲🇩", dial_code: "+373" },
  { name: "Monaco", code: "MC", flag: "🇲🇨", dial_code: "+377" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", dial_code: "+976" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", dial_code: "+382" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", dial_code: "+212" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", dial_code: "+258" },
  {
    name: "Myanmar (formerly Burma)",
    code: "MM",
    flag: "🇲🇲",
    dial_code: "+95",
  },
  { name: "Namibia", code: "NA", flag: "🇳🇦", dial_code: "+264" },
  { name: "Nauru", code: "NR", flag: "🇳🇷", dial_code: "+674" },
  { name: "Nepal", code: "NP", flag: "🇳🇵", dial_code: "+977" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", dial_code: "+31" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", dial_code: "+64" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", dial_code: "+505" },
  { name: "Niger", code: "NE", flag: "🇳🇪", dial_code: "+227" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", dial_code: "+234" },
  { name: "North Korea", code: "KP", flag: "🇰🇵", dial_code: "+850" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", dial_code: "+389" },
  { name: "Norway", code: "NO", flag: "🇳🇴", dial_code: "+47" },
  { name: "Oman", code: "OM", flag: "🇴🇲", dial_code: "+968" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", dial_code: "+92" },
  { name: "Palau", code: "PW", flag: "🇵🇼", dial_code: "+680" },
  { name: "Palestine State", code: "PS", flag: "🇵🇸", dial_code: "+970" },
  { name: "Panama", code: "PA", flag: "🇵🇦", dial_code: "+507" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", dial_code: "+675" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", dial_code: "+595" },
  { name: "Peru", code: "PE", flag: "🇵🇪", dial_code: "+51" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", dial_code: "+63" },
  { name: "Poland", code: "PL", flag: "🇵🇱", dial_code: "+48" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", dial_code: "+351" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", dial_code: "+974" },
  { name: "Romania", code: "RO", flag: "🇷🇴", dial_code: "+40" },
  { name: "Russia", code: "RU", flag: "🇷🇺", dial_code: "+7" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", dial_code: "+250" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flag: "🇰🇳",
    dial_code: "+1-869",
  },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", dial_code: "+1-758" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "🇻🇨",
    dial_code: "+1-784",
  },
  { name: "Samoa", code: "WS", flag: "🇼🇸", dial_code: "+685" },
  { name: "San Marino", code: "SM", flag: "🇸🇲", dial_code: "+378" },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", dial_code: "+239" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", dial_code: "+966" },
  { name: "Senegal", code: "SN", flag: "🇸🇳", dial_code: "+221" },
  { name: "Serbia", code: "RS", flag: "🇷🇸", dial_code: "+381" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", dial_code: "+248" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", dial_code: "+232" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", dial_code: "+65" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", dial_code: "+421" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", dial_code: "+386" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", dial_code: "+677" },
  { name: "Somalia", code: "SO", flag: "🇸🇴", dial_code: "+252" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", dial_code: "+27" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", dial_code: "+82" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", dial_code: "+211" },
  { name: "Spain", code: "ES", flag: "🇪🇸", dial_code: "+34" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", dial_code: "+94" },
  { name: "Sudan", code: "SD", flag: "🇸🇩", dial_code: "+249" },
  { name: "Suriname", code: "SR", flag: "🇸🇷", dial_code: "+597" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", dial_code: "+46" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", dial_code: "+41" },
  { name: "Syria", code: "SY", flag: "🇸🇾", dial_code: "+963" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", dial_code: "+886" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", dial_code: "+992" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", dial_code: "+255" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", dial_code: "+66" },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", dial_code: "+670" },
  { name: "Togo", code: "TG", flag: "🇹🇬", dial_code: "+228" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", dial_code: "+676" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", dial_code: "+1-868" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", dial_code: "+216" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", dial_code: "+90" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", dial_code: "+993" },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", dial_code: "+688" },
  { name: "Uganda", code: "UG", flag: "🇺🇬", dial_code: "+256" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", dial_code: "+380" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", dial_code: "+971" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", dial_code: "+44" },
  { name: "United States of America", code: "US", flag: "🇺🇸", dial_code: "+1" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", dial_code: "+598" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", dial_code: "+998" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", dial_code: "+678" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", dial_code: "+58" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", dial_code: "+84" },
  { name: "Yemen", code: "YE", flag: "🇾🇪", dial_code: "+967" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", dial_code: "+260" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", dial_code: "+263" },
];
